# Generated by Django 2.2 on 2019-04-29 12:17

from django.db import migrations, models
from datetime import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('LaserProductionTracker', '0003_product_product_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laserproductionrun',
            name='time_finished',
        ),
        migrations.RemoveField(
            model_name='laserproductionrun',
            name='time_started',
        ),
        migrations.AddField(
            model_name='laserproductionrun',
            name='assembly_time_finished',
            field=models.DateTimeField(default=datetime.now),
        ),
        migrations.AddField(
            model_name='laserproductionrun',
            name='assembly_time_started',
            field=models.DateTimeField(default=datetime.now),
        ),
        migrations.AddField(
            model_name='laserproductionrun',
            name='laser_time_finished',
            field=models.DateTimeField(default=datetime.now),
        ),
        migrations.AddField(
            model_name='laserproductionrun',
            name='laser_time_started',
            field=models.DateTimeField(default=datetime.now),
        ),
        migrations.AddField(
            model_name='laserproductionrun',
            name='packaging_time_finished',
            field=models.DateTimeField(default=datetime.now),
        ),
        migrations.AddField(
            model_name='laserproductionrun',
            name='packaging_time_started',
            field=models.DateTimeField(default=datetime.now),
        ),
        migrations.AddField(
            model_name='laserproductionrun',
            name='shrink_time_finished',
            field=models.DateTimeField(default=datetime.now),
        ),
        migrations.AddField(
            model_name='laserproductionrun',
            name='shrink_time_started',
            field=models.DateTimeField(default=datetime.now),
        ),
    ]
